#!/bin/bash

# Not run as root
if [ "$EUID" -eq 0 ]
  then echo "Please do not run as root"
  exit
fi

sudo apt install figlet -y

# Display a message
figlet -f slant "Proxmox Setup"
echo "This script will setup Proxmox network configuration"

# Wait for 5 seconds
sleep 5

# Update and upgrade packages
sudo apt update
sudo apt upgrade -y

# Install neofetch
sudo apt install neofetch -y

# Display system information using neofetch
neofetch

# Wait for 5 seconds
sleep 5

# Modify /etc/network/interfaces
sudo tee /etc/network/interfaces > /dev/null <<EOF
# network interface settings; autogenerated
# Please do NOT modify this file directly, unless you know what
# you're doing.
#
# If you want to manage parts of the network configuration manually,
# please utilize the 'source' or 'source-directory' directives to do
# so.
# PVE will preserve these directives, but will NOT read its network
# configuration from sourced files, so do not attempt to move any of
# the PVE managed interfaces into external files!

source /etc/network/interfaces.d/*

auto lo
iface lo inet loopback

iface enP4p65s0 inet manual

iface enP3p49s0 inet manual

auto vmbr0
iface vmbr0 inet static
	address 192.168.1.199/24
	gateway 192.168.1.254
	bridge-ports enP3p49s0
	bridge-stp off
	bridge-fd 0
	bridge-vlan-aware yes
	bridge-vids 2-4094

auto vmbr1
iface vmbr1 inet static
	address 192.168.1.200/24
	bridge-ports enP4p65s0
	bridge-stp off
	bridge-fd 0
	bridge-vlan-aware yes
	bridge-vids 2-4094
EOF

# Modify /etc/hosts
sudo tee /etc/hosts > /dev/null <<EOF
127.0.0.1   localhost.localdomain localhost
192.168.1.199    prox4m1.proxmox.com prox4m1
::1         localhost ip6-localhost ip6-loopback
fe00::0     ip6-localnet
ff00::0     ip6-mcastprefix
ff02::1     ip6-allnodes
ff02::2     ip6-allrouters
EOF

# Display a message
figlet -f slant "Proxmox network setup completed"
echo "Please run proxmox_install_OPi5Plus script as root to install Proxmox"

# Wait for 5 seconds
sleep 5

# Restart network
sudo systemctl restart networking